"""empty message

Revision ID: 63903d17e09a
Revises: 37b873fddf39
Create Date: 2019-04-13 23:13:07.757928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63903d17e09a'
down_revision = '37b873fddf39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.Column('caption', sa.String(length=80), nullable=True),
    sa.Column('created_on', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Users', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('Users', 'userid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('userid', sa.INTEGER(), server_default=sa.text('nextval(\'"Users_userid_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.drop_column('Users', 'id')
    op.drop_table('Posts')
    # ### end Alembic commands ###
